Tests evolved to cover custom apps. Support for drivers in documentation

diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -1,6 +1,8 @@
 #!/bin/bash -e
 SCRIPT_DIR=$(dirname $0)
 test_dir="$(readlink -zf $(dirname "${BASH_SOURCE[0]}"))"
+log_file=$(mktemp -u --suffix=.log)
+s2i_log_file=$(mktemp -u --suffix=.log)
 cid_file=$(mktemp -u --suffix=.cid)
 DATASOURCE_ENV_VAR="-e DB_SERVICE_PREFIX_MAPPING=TEST-postgresql=test -e TEST_POSTGRESQL_SERVICE_HOST=localhost \
 -e TEST_POSTGRESQL_SERVICE_PORT=5432 -e test_DATABASE=demo -e test_JNDI="java:jboss/datasources/test-postgresql" \
@@ -8,6 +10,8 @@ DATASOURCE_ENV_VAR="-e DB_SERVICE_PREFIX_MAPPING=TEST-postgresql=test -e TEST_PO
 -e test_USERNAME=demo"
 
 JSON_LOGGING_ENV_VAR="-e ENABLE_JSON_LOGGING=true"
+
+EXTERNAL_DATASOURCE_ENV="-e ENV_FILES=/opt/jboss/wildfly/standalone/configuration/datasources.env"
 
 # Since we built the image locally, we don't want S2I attempt to pull
 # it from Docker hub
@@ -27,11 +31,9 @@ container_ip() {
   docker inspect --format="{{ .NetworkSettings.IPAddress }}" $(cat $cid_file)
 }
 
-run_s2i_build() {
-  s2i build ${s2i_args} file://${test_dir}/test-app ${IMAGE_NAME}:${IMAGE_VERSION} ${IMAGE_NAME}-testapp $@
-}
-
 prepare() {
+  app=$1
+  shift
   if ! image_exists ${IMAGE_NAME}:${IMAGE_VERSION}; then
     echo "ERROR: The image ${IMAGE_NAME}:${IMAGE_VERSION} must exist before this script is executed."
     exit 1
@@ -40,26 +42,19 @@ prepare() {
     echo "ERROR: The image ${RUNTIME_IMAGE_NAME}:${IMAGE_VERSION} must exist before this script is executed."
     exit 1
   fi
-  # TODO: S2I build require the application is a valid 'GIT' repository, we
-  # should remove this restriction in the future when a file:// is used.
-  pushd ${test_dir}/test-app >/dev/null
-  git init
-  git config user.email "build@localhost" && git config user.name "builder"
-  git add -A && git commit -m "Sample commit" || true
-  popd >/dev/null
-  run_s2i_build $@
+  s2i build ${s2i_args} file://${test_dir}/$app ${IMAGE_NAME}:${IMAGE_VERSION} ${IMAGE_NAME}-testapp $@ >& $s2i_log_file
 }
 
 run_test_application() {
-  docker run $@ --rm --cidfile=${cid_file} ${IMAGE_NAME}-testapp  >& /dev/null
+  docker run $@ --rm --cidfile=${cid_file} ${IMAGE_NAME}-testapp >& $log_file
 }
 
 run_builder_image() {
-  docker run $@ --rm --cidfile=${cid_file} ${IMAGE_NAME} >& /dev/null
+  docker run $@ --rm --cidfile=${cid_file} ${IMAGE_NAME} >& $log_file
 }
 
 run_test_application-rt() {
-  docker run --rm $1 --cidfile=${cid_file} ${RUNTIME_IMAGE_NAME}-testapp  >& /dev/null
+  docker run --rm $1 --cidfile=${cid_file} ${RUNTIME_IMAGE_NAME}-testapp  >& $log_file
 }
 
 cleanup() {
@@ -79,11 +74,16 @@ cleanup() {
   rm -f $cid_file
 }
 
+cleanupFinal() {
+  rm -f $log_file
+  rm -f $s2i_log_file
+}
+
 check_result() {
   local result="$1"
   if [[ "$result" != "0" ]]; then
     cleanup 1
-    echo "S2I image '${IMAGE_NAME}' test FAILED (exit code: ${result})"
+    echo "S2I image '${IMAGE_NAME}' test FAILED (exit code: ${result}), last container execution log file in $log_file"
     exit $result
   fi
 }
@@ -138,15 +138,19 @@ test_config() {
 }
 
 test_datasource() {
-  docker exec $(cat $cid_file) cat /wildfly/standalone/configuration/standalone.xml | grep pool-name=\"test_postgresql-test\"
+  docker exec $(cat $cid_file) cat /wildfly/standalone/configuration/standalone.xml | grep pool-name=\"$1\"
   check_result $? 
-  docker exec $(cat $cid_file) cat /opt/jboss/wildfly/standalone/configuration/standalone.xml | grep pool-name=\"test_postgresql-test\"
+  docker exec $(cat $cid_file) cat /opt/jboss/wildfly/standalone/configuration/standalone.xml | grep pool-name=\"$1\"
 }
 
 test_builtin_datasource() {
   docker exec $(cat $cid_file) cat /opt/jboss/wildfly/standalone/configuration/standalone.xml | grep pool-name=\"MySQLDS\"
   check_result $?
   docker exec $(cat $cid_file) cat /opt/jboss/wildfly/standalone/configuration/standalone.xml | grep pool-name=\"PostgreSQLDS\"
+}
+
+test_driver() {
+  docker exec $(cat $cid_file) cat /opt/jboss/wildfly/standalone/configuration/standalone.xml | grep "driver name=\"$1\""
 }
 
 test_json_logging() {
@@ -182,10 +186,12 @@ EOF
 }
 
 echo "Testing image $IMAGE_NAME"
+echo "Last s2i execution is logged in $s2i_log_file"
+echo "Last container execution is logged in $log_file"
 
-# Test deployment in default server
+echo "### Test deployment in default server."
 
-prepare
+prepare test-app
 
 # Verify the 'usage' script is working properly
 run_test_usage
@@ -206,7 +212,7 @@ check_result $?
 
 cleanup 0
 
-# Test execution of builder image and addition of datasource and json logging
+echo "### Test execution of builder image and addition of datasource and json logging."
 cid_file=$(mktemp -u --suffix=.cid)
 run_builder_image $DATASOURCE_ENV_VAR $JSON_LOGGING_ENV_VAR &
 
@@ -217,7 +223,7 @@ wait_for_cid
 test_connection
 check_result $?
 
-test_datasource
+test_datasource test_postgresql-test
 check_result $?
 
 test_builtin_datasource
@@ -228,9 +234,9 @@ check_result $?
 
 cleanup 0
 
-# Test deployment in galleon provisioned default server.
+echo "### Test deployment in galleon provisioned default server."
 cid_file=$(mktemp -u --suffix=.cid)
-prepare "-e GALLEON_PROVISION_SERVER=os-standalone-profile"
+prepare  test-app "-e GALLEON_PROVISION_SERVER=os-standalone-profile"
  
 run_test_application $DATASOURCE_ENV_VAR $JSON_LOGGING_ENV_VAR &
 # Wait for the container to write it's CID file
@@ -240,10 +246,16 @@ wait_for_cid
 test_connection
 check_result $?
 
-test_datasource
+test_datasource test_postgresql-test
 check_result $?
 
 test_builtin_datasource
+check_result $?
+
+test_driver postgresql
+check_result $?
+
+test_driver mysql
 check_result $?
 
 test_json_logging
@@ -251,10 +263,10 @@ check_result $?
 
 cleanup 0
 
-# Test deployment in custom server
+echo "### Test deployment in cloud-profile server."
 
 cid_file=$(mktemp -u --suffix=.cid)
-prepare "-e GALLEON_PROVISION_SERVER=cloud-profile"
+prepare test-app "-e GALLEON_PROVISION_SERVER=cloud-profile"
 
 #JSON logging should have no effect on the configuration, server should start properly
 # although logging subsystem is not present in cloud-profile.
@@ -270,12 +282,40 @@ check_result $?
 test_galleon cloud-profile
 check_result $?
 
-test_datasource
+test_datasource test_postgresql-test
 check_result $?
 cleanup 0
 
+echo "### Test external driver created during s2i."
+
 cid_file=$(mktemp -u --suffix=.cid)
-prepare "-e GALLEON_PROVISION_SERVER=jaxrs"
+prepare test-app-custom
+
+#Add an external datasource configured from env file.
+run_test_application $EXTERNAL_DATASOURCE_ENV &
+
+# Wait for the container to write it's CID file
+#
+wait_for_cid
+
+test_connection
+check_result $?
+
+test_galleon cloud-profile
+check_result $?
+
+#  test_driver testpostgresql
+check_result $?
+
+#test_datasource test-TEST
+check_result $?
+
+cleanup 0
+
+echo "### Test deployment in jaxrs server"
+
+cid_file=$(mktemp -u --suffix=.cid)
+prepare test-app "-e GALLEON_PROVISION_SERVER=jaxrs"
  
 run_test_application &
 # Wait for the container to write it's CID file
@@ -290,9 +330,9 @@ check_result $?
 
 cleanup 0
 
-# Test chained build
+echo "### Test chained build"
 cid_file=$(mktemp -u --suffix=.cid)
-prepare "-e GALLEON_PROVISION_SERVER=jaxrs"
+prepare test-app "-e GALLEON_PROVISION_SERVER=jaxrs"
 
 build_chained_build
 check_result $?
@@ -306,4 +346,5 @@ check_result $?
 
 cleanup 0
 
+cleanupFinal
 echo "Test SUCCESSFUL"
