Fix for #181, Make release github-action to not tag with latest

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -83,24 +83,22 @@ jobs:
                echo "ERROR no builder image version found"
                exit 1
             fi
-            BUILDER_IMAGE="quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7:${BUILDER_IMAGE_VERSION}"
-            RUNTIME_IMAGE="quay.io/${{ secrets.QUAY_REPO }}/wildfly-runtime-centos7:${RUNTIME_IMAGE_VERSION}"
-
-            LATEST_BUILDER_IMAGE="quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7:latest"
-            LATEST_RUNTIME_IMAGE="quay.io/${{ secrets.QUAY_REPO }}/wildfly-runtime-centos7:latest"
-
+            if [ ${BUILDER_IMAGE_VERSION} != ${RUNTIME_IMAGE_VERSION} ]; then
+               echo "ERROR builder and runtime images version are not equal: builder ${BUILDER_IMAGE_VERSION}, runtime ${RUNTIME_IMAGE_VERSION}"
+               exit 1
+            fi
+            WILDFLY_IMAGE_VERSION=${BUILDER_IMAGE_VERSION}
+            BUILDER_IMAGE="quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7:${WILDFLY_IMAGE_VERSION}"
+            RUNTIME_IMAGE="quay.io/${{ secrets.QUAY_REPO }}/wildfly-runtime-centos7:${WILDFLY_IMAGE_VERSION}"
+            echo "WILDFLY_IMAGE_VERSION=${WILDFLY_IMAGE_VERSION}" >> $GITHUB_ENV
             echo Pushing to quay.io
             echo BUILDER_IMAGE: ${BUILDER_IMAGE}
             echo RUNTIME_IMAGE: ${RUNTIME_IMAGE}
             docker login -u="${{ secrets.QUAY_USERNAME }}" -p="${{ secrets.QUAY_PASSWORD }}" quay.io
-            docker tag wildfly/wildfly-centos7:${BUILDER_IMAGE_VERSION} ${BUILDER_IMAGE}
-            docker tag wildfly/wildfly-centos7:${BUILDER_IMAGE_VERSION} ${LATEST_BUILDER_IMAGE}
+            docker tag wildfly/wildfly-centos7:${WILDFLY_IMAGE_VERSION} ${BUILDER_IMAGE}
             docker push ${BUILDER_IMAGE}
-            docker push ${LATEST_BUILDER_IMAGE}
-            docker tag wildfly/wildfly-runtime-centos7:${RUNTIME_IMAGE_VERSION} ${RUNTIME_IMAGE}
-            docker tag wildfly/wildfly-runtime-centos7:${RUNTIME_IMAGE_VERSION} ${LATEST_RUNTIME_IMAGE}
+            docker tag wildfly/wildfly-runtime-centos7:${WILDFLY_IMAGE_VERSION} ${RUNTIME_IMAGE}
             docker push ${RUNTIME_IMAGE}
-            docker push ${LATEST_RUNTIME_IMAGE}
       - name: Build PostgreSQL example and push to quay.io
         run: |
           s2i build https://github.com/wildfly/wildfly-s2i \
@@ -108,7 +106,7 @@ jobs:
           -r master \
           --context-dir test/test-app-postgres \
           --loglevel=5 \
-          quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7:latest \
+          quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7:${{ env.WILDFLY_IMAGE_VERSION }} \
           wildfly-s2i-builder-image
           docker tag wildfly-s2i-builder-image:latest quay.io/${{ secrets.QUAY_REPO }}/taskrs-app:latest
           docker push quay.io/${{ secrets.QUAY_REPO }}/taskrs-app:latest
@@ -118,7 +116,7 @@ jobs:
           -e MAVEN_ARGS_APPEND=-Pee8 \
           -e S2I_SOURCE_DEPLOYMENTS_DIR=clusterbench-ee8-ear/target \
           -e GALLEON_PROVISION_LAYERS=cloud-server,web-clustering,ejb,-ejb-local-cache,ejb-dist-cache,jsf \
-          quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7:latest \
+          quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7:${{ env.WILDFLY_IMAGE_VERSION }} \
           wildfly-s2i-builder-image
           docker tag wildfly-s2i-builder-image:latest quay.io/${{ secrets.QUAY_REPO }}/clusterbench:latest
           docker push quay.io/${{ secrets.QUAY_REPO }}/clusterbench:latest
@@ -141,4 +139,4 @@ jobs:
           -f https://raw.githubusercontent.com/wildfly/wildfly-charts/main/examples/microprofile-config/microprofile-config-app-s2i.yaml \
           --set build.s2i.builderImage=quay.io/${{ secrets.QUAY_REPO }}/wildfly-centos7 \
           --set build.s2i.runtimeImage=quay.io/${{ secrets.QUAY_REPO }}/wildfly-runtime-centos7 \
-          --set build.s2i.version=latest
+          --set build.s2i.version=${{ env.WILDFLY_IMAGE_VERSION }}
